### ISSUE TITLE
Forbidden when access /@jobs on localhost:[::1]:45668 is not local

### ISSUE THREAD

**Issue by yashen** [revel/modules#21]
go version is  go1.8 linux/amd64

**Comment by notzippy** [comment]
That is by design, see http://revel.github.io/modules/jobs.html . If you want to work on a feature to allow remote access (perhaps restricted) this is an area we are looking for enhancements in

**Comment by notzippy** [comment]
Additional thoughts,  one thing I have done in the past is to setup a LocalForward in my ssh [config file](https://www.digitalocean.com/community/tutorials/how-to-configure-custom-connection-options-for-your-ssh-client) then you can access the jobs page and it will display because it thinks you are local

**Comment by yashen** [comment]
I am local.
in status.go
```
	if !strings.HasPrefix(remoteAddress, "127.0.0.1") && !strings.HasPrefix(remoteAddress, "::1") {
		return c.Forbidden("%s is not local", remoteAddress)
	}
```
If my remoteAddress is ::1:45668,it will pass,but now my my remoteAddress is [::1]:45668,
I think perhaps golang's lib changed somewhere

**Comment by notzippy** [comment]
OK, thanks for the details, will schedule to fix bug
